### ISSUE TITLE
multihost_runner.py: number of devices does not match the product of the parallelism

### ISSUE THREAD

**Issue by rlrs** [google/maxtext#30]
I'm testing out multihost training, and following along with the readme for "Quick Experiments on Multiple Slices" (except, I'm not using queued resources because those also do not work for me).
I have two v2-8 TPU VMs running, and another non-TPU VM that I'm running commands on.

This is what happens, however:
`$ python3 multihost_runner.py --TPU_PREFIX='tpu' --COMMAND='python3 MaxText/train.py MaxText/configs/base.yml run_name=RUN-2-SLICES dcn_data_parallelism=2'`

```
Starting multihost runner...
2 slices found.
[t=0.00, SCP] Completed 0/2, slice 0 worker 0 still working...
[t=1.00, SCP] Completed 0/2, slice 0 worker 0 still working...
[t=2.01, SCP] Completed 0/2, slice 0 worker 0 still working...
SCP: Attempting to connect to worker 0...
[t=3.01, SCP] Completed 0/2, slice 0 worker 0 still working...
[t=4.01, SCP] Completed 0/2, slice 0 worker 0 still working...
script_dir_zip_2023-05-06-11-18-22.tar.gz                                                                                                                                        100%  417KB  60.7MB/s   00:00
[t=5.01, SCP] Completed 0/2, slice 0 worker 0 still working...
[t=6.01, SCP] Completed 2/2...
Running main command, logs located in: /tmp/2023-05-06-11-18-22/
[t=0.01, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
...

Searching for existing processes on device accel0...
No existing processes found.
[t=5.01, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
...

2023-05-06 11:18:36.790902: I external/org_tensorflow/tensorflow/compiler/xla/stream_executor/tpu/tpu_initializer_helper.cc:269] Libtpu path is: /home/rlrs_alexandra_gmail_com/.local/lib/python3.8/site-packages/
libtpu/libtpu.so
[t=9.02, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
...

2023-05-06 11:18:43.741793: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:168] XLA service 0x358f380 initialized for platform TPU (this does not guarantee that XLA will be used). Devices:
2023-05-06 11:18:43.741840: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TPU, 2a886c8
2023-05-06 11:18:43.741851: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): TPU, 2a886c8
2023-05-06 11:18:43.741861: I external/org_tenso[t=15.02, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
rflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): TPU, 2a886c8
2023-05-06 11:18:43.741872: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): TPU, 2a886c8
2023-05-06 11:18:43.741882: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (4): TPU, 2a886c8
2023-05-06 11:18:43.741891: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (5): TPU, 2a886c8
2023-05-06 11:18:43.741901: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (6): TPU, 2a886c8
2023-05-06 11:18:43.741911: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (7): TPU, 2a886c8
2023-05-06 11:18:43.765380: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/tfrt_cpu_pjrt_client.cc:218] TfrtCpuClient created.
[t=16.02, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
...
2023-05-06 11:19:03.221482: I tensorflow/compiler/xla/stream_executor/tpu/tpu_initializer_helper.cc:266] Libtpu path is: /home/rlrs_alexandra_gmail_com/.local/lib/python3.8/site-packages/libtpu/libtpu.so
[t=35.05, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
2023-05-06 11:19:04.591554: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[t=36.05, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
...

Initialized persistent compilation cache at /home/rlrs_alexandra_gmail_com/jax_cache
Found 8 devices.
Creating checkpoint manager...
I0506 11:19:17.302592 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit_convert_element_type' because it took < 1.00 seconds to compile (0.03s)
I0506 11:19:17.325799 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit_broadcast_in_dim' because it took < 1.00 seconds to compile (0.02s)
I0506 11:19:17.455217 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'pmap__psum' because it took < 1.00 seconds to compile (0.12s)
I0506 11:19:17.484924 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit_broadcast_in_dim' because it took < 1.00 seconds to compile (0.02s)
I0506 11:19:17.611627 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'pmap__psum' because it took < 1.00 seconds to compile (0.11s)
I0506 11:19:17.614650 140423533554752 distributed.py:68] Starting JAX distributed service on 10.128.0.11:33429
2023-05-06 11:19:17.615705: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/service.cc:522] Experimental coordination service is enabled.
2023-05-06 11:19:17.615970: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/service.cc:554] Jax service listening on 10.128.0.11:33429
I0506 11:19:17.616165 140423533554752 distributed.py:79] Connecting to JAX distributed service on 10.128.0.11:33429
2023-05-06 11:19:17.616817: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service.cc:525] /job:jax_worker/replica:0/task:0 has connected to coordination service. Incarnat
ion: 7064756694357617212
2023-05-06 11:19:17.616980: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service_agent.cc:298] Coordination agent has successfully connected.
2023-05-06 11:19:17.617244: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:508] Connected to distributed JAX controller
[t=49.06, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
I0506 11:19:18.599849 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'pmap__psum' because it took < 1.00 seconds to compile (0.12s)
[t=50.06, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
Checkpoint manager created!
I0506 11:19:18.818627 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit_shift_right_logical' because it took < 1.00 seconds to compile (0.02s)
I0506 11:19:18.839082 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit_convert_element_type' because it took < 1.00 seconds to compile (0.02s)
I0506 11:19:18.860087 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit_reshape' because it took < 1.00 seconds to compile (0.02s)
I0506 11:19:18.882867 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit__lambda_' because it took < 1.00 seconds to compile (0.02s)
I0506 11:19:18.906052 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit_concatenate' because it took < 1.00 seconds to compile (0.02s)
I0506 11:19:19.128638 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit__threefry_split_original' because it took < 1.00 seconds to compile (0.11s)
I0506 11:19:19.153988 140423533554752 dispatch.py:1131] Not writing persistent cache entry for 'jit__unstack' because it took < 1.00 seconds to compile (0.02s)
Devices: [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0), TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1), TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0), Tpu
Device(id=3, process_index=0, coords=(1,0,0), core_on_chip=1), TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0), TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1), TpuDevice(id=6,
process_index=0, coords=(1,1,0), core_on_chip=0), TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)] (num_devices: 8)
Traceback (most recent call last):
  File "MaxText/train.py", line 349, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "MaxText/train.py", line 345, in main
    train_loop(pyconfig.config)
  File "MaxText/train.py", line 278, in train_loop
    devices_array = max_utils.create_device_mesh(config)
  File "/home/rlrs_alexandra_gmail_com/2023-05-06-11-18-22/MaxText/max_utils.py", line 78, in create_device_mesh
    assert (
**AssertionError: Number of devices 8         does not match the product of the parallelism 16**
2023-05-06 11:19:19.174563: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:516] Distributed task shutdown initiated.
2023-05-06 11:19:19.174587: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service_agent.cc:464] Coordination agent has initiated Shutdown().
2023-05-06 11:19:19.174862: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service.cc:1136] Shutdown barrier in coordination service has passed.
2023-05-06 11:19:19.174911: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service.cc:630] /job:jax_worker/replica:0/task:0 has disconnected from coordination service.
2023-05-06 11:19:19.175025: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service_agent.cc:483] Coordination agent has successfully shut down.
2023-05-06 11:19:19.175146: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:518] Distributed task shutdown result: OK
2023-05-06 11:19:19.175165: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/preemption/preemption_sync_manager.cc:166] Cancelled call to retrieve preemption notice. This is expected upon program shu
tdown.
2023-05-06 11:19:19.175203: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/service.cc:576] Jax service shutting down
2023-05-06 11:19:19.176923: I external/org_tensorflow/tensorflow/tsl/distributed_runtime/preemption/preemption_sync_manager.cc:139] Preemption sync protocol cancelled by notifier: CANCELLED: Preemption notifier
is being deleted.. This is expected during program shutdown.
[t=51.07, MAIN COMMAND] Completed 0/2, slice 0 worker 0 still working...
Exception ignored in: <function GCSRecordWriter.__del__ at 0x7fb4b803daf0>
Traceback (most recent call last):
... etc
```

Seems like the TPU node is not aware that it's multislice? What am I doing wrong?

Edit:
A little update from my side. I realize that maybe `jax.distributed` does not actually support connection TPUs across pods? Even if I try to manually connect two v2-8 VMs with `jax.distributed.initialize()`, they end up with `jax.process_count()` returning 1.

**Comment by priyanka-ganesha** [comment]
Hi, thanks for your question!

You’re right in thinking that the nodes are not aware that they’re in multislice. Multislice workloads are made possible by Megascale XLA flags which make it possible for TPU slices to work with each other. This is where QueuedResources are key, as they set up these MXLA flags during initialization.

We would have expected v2 users to typically use single slice. Is there a specific reason you're experimenting with multislice on v2? We'd love to know so we can give you better guidance on what to try next.

**Comment by rlrs** [comment]
Thanks a lot for your response, that's about what I expected. My hope was that I could try to use some of the free resources allocated through TPU Research Cloud for larger scale training. These resources are mainly v2-8 slices on us-central1-f.

With this information I will stop going down this path, so it's good to know.

**Comment by rwitten** [comment]
OK, we will make this as closed. I wish we could be more helpful here!
