### ISSUE TITLE
Issues running end_to_end/test_mistral.sh

### ISSUE THREAD

**Issue by MicPie** [google/maxtext#412]
When running `bash end_to_end/test_mistral.sh` this line
```
gsutil -m cp -r gs://maxtext-external/mistral-7B-v0.1 /tmp
```
leads to the following error:
```
AccessDeniedException: 403 316027847246-compute@developer.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
CommandException: 1 file/object could not be transferred.
```
Did the path changed or can I get the needed files from somewhere else?

_Edit:_
Running
```
git clone https://huggingface.co/mistralai/Mistral-7B-v0.1
```
and using the corresponding path for `--base-model-path` leads to this error:
```
Loading the base model from /home/MMP/Mistral-7B-v0.1
Traceback (most recent call last):
  File "/home/MMP/maxtext/MaxText/llama_or_mistral_ckpt.py", line 309, in <module>
    convert(args.base_model_path, args.maxtext_model_path, args.model_size)
  File "/home/MMP/maxtext/MaxText/llama_or_mistral_ckpt.py", line 127, in convert
    'scale': pytorch_vars[0]['norm.weight'].type(torch.float16).numpy()
IndexError: list index out of range
```

**Comment by MicPie** [comment]
Similar issue with `bash end_to_end/test_llama2.sh`:
```
...
Model path: gs://maxtext-llama/llama2-7b/tokenizer.llama2
Traceback (most recent call last):
  File "/home/MMP/maxtext/MaxText/decode.py", line 278, in <module>
    app.run(main)
  File "/home/MMP/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/MMP/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/MMP/maxtext/MaxText/decode.py", line 275, in main
    decode_loop(pyconfig.config)
  File "/home/MMP/maxtext/MaxText/decode.py", line 187, in decode_loop
    _, _, sp_tokenizer = create_data_iterator_with_tokenizer(config, mesh, add_bos = True, add_eos=False)
  File "/home/MMP/maxtext/MaxText/input_pipeline/input_pipeline_interface.py", line 123, in create_data_iterator_with_tokenizer
    return make_c4_train_iterator_and_tokenizer(config, mesh, add_bos, add_eos)
  File "/home/MMP/maxtext/MaxText/input_pipeline/input_pipeline_interface.py", line 55, in make_c4_train_iterator_and_tokenizer
    train_iter, _, _, sp_tokenizer = _tfds_data_processing.preprocess_dataset(
  File "/home/MMP/maxtext/MaxText/input_pipeline/_tfds_data_processing.py", line 213, in preprocess_dataset
    sp_tokenizer = tokenizer.load_tokenizer(vocab_path=vocab_path,
  File "/home/MMP/maxtext/MaxText/tokenizer.py", line 48, in load_tokenizer
    sp_tokenizer = _load_sentencepiece_tokenizer(vocab_path, add_bos, add_eos)
  File "/home/MMP/maxtext/MaxText/tokenizer.py", line 40, in _load_sentencepiece_tokenizer
    sp_model = model_fp.read()
  File "/home/MMP/.local/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    length = self.size() - self.tell()
  File "/home/MMP/.local/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 96, in size
    return stat(self.__name).length
  File "/home/MMP/.local/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 908, in stat
    return stat_v2(filename)
  File "/home/MMP/.local/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 924, in stat_v2
    return _pywrap_file_io.Stat(compat.path_to_str(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 403 with body '{
  "error": {
    "code": 403,
    "message": "316027847246-compute@developer.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).",
    "errors": [
      {
        "message": "316027847246-compute@developer.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist)."'
	 when reading metadata of gs://maxtext-llama/llama2-7b/tokenizer.llama2
```

**Comment by rwitten** [comment]
Sorry, we should mark these as google-internal only. @RissyRan can you figure out why there is an issue with the model version @MicPie is using? (Does it work for you, etc?)

**Comment by RissyRan** [comment]
Hi @MicPie,

Currently, the GCS bucket `gs://maxtext-external` is still internal only. The huggingface model may not be feasible here due to different file format. The converter looks for model ends with `.pth`.

For mistral test, can you try commands below to workaround (under maxtext dir)?

```
bash setup.sh
pip3 install torch
wget https://files.mistral-7b-v0-1.mistral.ai/mistral-7B-v0.1.tar
tar -xf mistral-7B-v0.1.tar
```

Then, convert the checkpoint and run the test:

```
python3 MaxText/llama_or_mistral_ckpt.py --base-model-path <your_model_path_from_above> --model-size mistral-7b --maxtext-model-path <your_new_checkpoint_path>

python3 MaxText/decode.py MaxText/configs/base.yml load_parameters_path=<your_new_checkpoint_path>/0/default run_name=runner_mistral_test per_device_batch_size=1 model_name='mistral-7b' assets_path=<your_model_path_from_above> ici_tensor_parallelism=4 max_prefill_predict_length=4  max_target_length=16 prompt="I love to" autoregressive_decode_assert="read. I love to read about the Bible. I love" attention=dot_product
```

Let me know if you still meet issues.

**Comment by MicPie** [comment]
Hi @RissyRan and @rwitten!

Thank you for your fast reply! :-)

I had to add the `dataset_path` to `python3 MaxText/decode.py ...`  and now I get:
```
AttributeError: in user code:

    File "/home/MMP/maxtext/MaxText/tokenizer.py", line 63, in __call__  *
        features[k] = self.sp_tokenizer.tokenize(features[k])

    AttributeError: 'NoneType' object has no attribute 'tokenize'
```
I guess the correct tokenizer would be still needed, as outlined in this branch https://github.com/google/maxtext/tree/anisha-hf-tokenizer ?

**Comment by MicPie** [comment]
Ok, with these changes I could get it to run:

1.) Add import at the top:
```python
from transformers import AutoTokenizer
```

2.) In `decode_loop` change to HF tokenizer:
```python
  #_, _, sp_tokenizer = create_data_iterator_with_tokenizer(config, mesh, add_bos = True, add_eos=False)
  sp_tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-v0.1")
```

3.) Use HF tokenizer decode and encode:
```python
def decode_tokens(toks, tokenizer):
  #return tokenizer.detokenize(toks).numpy().decode("utf-8"), len(toks)
  return tokenizer.decode(toks), len(toks)

def encode_strings(strs, max_len, tokenizer, mesh):
  """Pack prefill prompts into Jax.Array. The prompts are `right-aligned`, i.e. padded with zeros and all ending on the same
     index."""
  tokenized_batch = np.zeros((len(strs), max_len), np.int32)
  positions = np.zeros((len(strs), max_len), np.int32)
  segment_ids = np.zeros((len(strs), max_len), np.int32)

  for i, s in enumerate(strs):
    #toks = tokenizer.tokenize(s).numpy()
    toks = tokenizer.encode(s, return_tensors="np")[0]
    assert toks.shape[0] <= max_len, f"We aren't able to tokenize input {i}, it is too long"
    prompt = toks
    start_index = max_len - prompt.shape[0]
    tokenized_batch[i, start_index:] = prompt
    padded_start_index = start_index
    segment_ids[i, padded_start_index:] = common_types.DECODING_ACTIVE_SEQUENCE_INDICATOR
    positions[i, padded_start_index:] = np.arange(len(prompt))
  return jax.device_put(tokenized_batch, jax.sharding.NamedSharding(mesh, P())),\
         jax.device_put(positions, jax.sharding.NamedSharding(mesh, P())),\
         jax.device_put(segment_ids, jax.sharding.NamedSharding(mesh, P()))
```

Output:
```
...
restoring params from load_parameters_from_path='/home/MMP/maxtext/mistral-7B-v0.1_export/0/default'
I0214 12:39:10.199224 140715856316416 checkpointer.py:164] Restoring item from /home/MMP/maxtext/mistral-7B-v0.1_export/0/default.
I0214 12:39:31.084964 140715856316416 checkpointer.py:167] Finished restoring checkpoint from /home/MMP/maxtext/mistral-7B-v0.1_export/0/default.
Number of model params=7.242 billion, memory usage=26.978GB, bytes per param=4.000
Computed prefill cache
Number of cache entries=0.004 billion, memory usage=0.008GB, bytes per cache=2.001
Total memory (for cache and params) 26.985 GB
Completion: `I love to` -> `read. I love to read about the Bible. I love`
Did 11 steps in 0.170 seconds for 4.0 sequences with a total memory footprint of 26.985 GB
Therefore, a per-generate time of 0.0155 seconds, a throughput of 258.3 tok/s and 435.6 GB/s/device
...
```

**Comment by rwitten** [comment]
Great news!

@RissyRan can we update our docs a little to make this clearer? Maybe a comment in each of the end_to_end files?

**Comment by RissyRan** [comment]
> Great news!
> 
> @RissyRan can we update our docs a little to make this clearer? Maybe a comment in each of the end_to_end files?

Sure thing! Will add some tips as comment for external users to run our Mistral, Mixtral, and Llama2 successfully.
