### ISSUE TITLE
Problems with a parameter checkpoint after training llama2-7b

### ISSUE THREAD

**Issue by Gugutse** [google/maxtext#425]
I’ve trained llama2-7b model with **int8 quantization**. The resulting checkpoints dir has the following structure:
```
- 0/:
-- commit_success.txt

-- default/:
--- _METADATA
--- _sharding
--- checkpoint
--- commit_success.txt
--- d/:
---- cacfeed1cb58f5...
---- ed63ba6da8ada7...
--- manifest.ocdbt
--- ocdbt.process_0/:
---- d/:
----- 028478f3dcd5b9...
----- 551917150ca2a8...
----- 8111cad0633e85...
---- manifest.ocdbt
--- ocdbt.process_1/
--- ...

-- metrics/

-10000/

-20000/

- ...
```
Following [this example](https://github.com/google/maxtext/blob/main/end_to_end/test_llama2.sh), I’m trying to generate a parameter checkpoint for further decoding:
```bash
export CHECKPOINT_PATH=gs://.../checkpoints/10000/default
export PARAMETER_CHECKPOINT_RUN=<MY_RUN_NAME>
python3 MaxText/generate_param_only_checkpoint.py MaxText/configs/base.yml load_full_state_path=$CHECKPOINT_PATH run_name=${PARAMETER_CHECKPOINT_RUN} model_name='llama2-7b' force_unroll=true
```
I get this output:
```bash
...
I0214 21:09:09.466111 140399213561856 checkpointer.py:167] Finished restoring checkpoint from gs://.../.../.../.../checkpoints/10000/default.
In input checkpoint Number of model params=6.738 billion
Save decode checkpoint at: gs://.../.../.../param_checkpoint/checkpoints/
I0214 21:09:10.367621 140399213561856 async_checkpointer.py:210] Commit thread error check finished successfully
I0214 21:09:12.452971 140399213561856 async_checkpointer.py:293] Async saving item to gs://.../.../.../param_checkpoint/checkpoints/0.
W0214 21:09:13.010293 140399213561856 type_handlers.py:399] SaveArgs.aggregate is deprecated, please use custom TypeHandler (https://orbax.readthedocs.io/en/latest/custom_handlers.html#typehandler) or contact Orbax team to migrate before May 1st, 2024.
I0214 21:09:23.297378 140316597466688 async_checkpointer.py:150] Starting commit to storage layer by process: 0
I0214 21:09:23.300883 140399213561856 checkpoint_manager.py:811] Beginning async checkpoint finalize.
saved an decode checkpoint at gs://.../.../.../param_checkpoint/checkpoints/
Successfully generated decode checkpoint at: gs://.../.../.../param_checkpoint/checkpoints/0/default
I0214 21:10:41.916716 140316597466688 async_checkpointer.py:158] Finished committing to storage layer by process: 0
I0214 21:10:41.917720 140317441869376 async_checkpointer.py:207] Commit thread joined successfully
```
The resulting dir `gs://.../.../.../param_checkpoint/checkpoints/0/default` with a parameter checkpoint has the following structure:
```bash
- _METADATA
- _sharding
- checkpoint
- ocdbt.process_0/:
-- d/:
--- 14159648ab13db...
--- 6bb79329658hjl...
--- caa39c6cfcajsk...
--- d852816bl798dj...
-- manifest.ocdbt
```
Following [this example](https://github.com/google/maxtext/blob/main/end_to_end/test_llama2.sh) further, I try to load a parameter checkpoint into [decode.py](http://decode.py/):
```bash
python3 MaxText/decode.py MaxText/configs/base.yml load_parameters_path=gs://.../.../.../param_checkpoint/checkpoints/0/default run_name=<MY_RUN_NAME> per_device_batch_size=1 model_name='llama2-7b' ici_tensor_parallelism=4 max_prefill_predict_length=4  max_target_length=16 prompt="I love to" autoregressive_decode_assert="read. I love to write. I love to share." attention=dot_product scan_layers=false
```
I get this error:
```bash
restoring params from load_parameters_from_path='gs://.../.../.../param_checkpoint/checkpoints/0/default'
Traceback (most recent call last):
  File "/home/.../2024-02-14-19-59-41/MaxText/decode.py", line 278, in <module>
    app.run(main)
  File "/home/.../.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/.../.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/.../2024-02-14-19-59-41/MaxText/decode.py", line 275, in main
    decode_loop(pyconfig.config)
  File "/home/.../2024-02-14-19-59-41/MaxText/decode.py", line 188, in decode_loop
    state, state_mesh_annotations = max_utils.setup_decode_state(
  File "/home/.../2024-02-14-19-59-41/MaxText/max_utils.py", line 334, in setup_decode_state
    return setup_initial_state(model, None, config, rng, mesh, checkpoint_manager, is_training)
  File "/home/.../2024-02-14-19-59-41/MaxText/max_utils.py", line 362, in setup_initial_state
    state, raw_params = checkpointing.load_state_if_possible(checkpoint_manager,
  File "/home/.../2024-02-14-19-59-41/MaxText/checkpointing.py", line 116, in load_state_if_possible
    full_restored_state = checkpointer.restore(p, item = abstract_param_train_state,\
  File "/home/.../.local/lib/python3.10/site-packages/orbax/checkpoint/checkpointer.py", line 163, in restore
    raise ValueError(f'Found incomplete checkpoint at {directory}.')
ValueError: Found incomplete checkpoint at gs://.../.../.../param_checkpoint/checkpoints/0/default.
```
Diving into the code, I realize that this error appears when there is no `commit_success.txt` file in the checkpoint dir. This file hasn’t been generated automatically by `generate_param_only_checkpoint.py`, despite the status `Successfully generated decode checkpoint` . I tried to add this file manually — I got this error:
```bash
I0216 11:10:42.486244 140477023528960 checkpointer.py:164] Restoring item from gs://.../.../param_checkpoint/checkpoints/0/default.
Traceback (most recent call last):
  File "/home/.../2024-02-14-19-59-41/MaxText/decode.py", line 278, in <module>
    app.run(main)
  File "/home/.../.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/.../.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/.../2024-02-14-19-59-41/MaxText/decode.py", line 275, in main
    decode_loop(pyconfig.config)
  File "/home/.../2024-02-14-19-59-41/MaxText/decode.py", line 188, in decode_loop
    state, state_mesh_annotations = max_utils.setup_decode_state(
  File "/home/.../2024-02-14-19-59-41/MaxText/max_utils.py", line 334, in setup_decode_state
    return setup_initial_state(model, None, config, rng, mesh, checkpoint_manager, is_training)
  File "/home/.../2024-02-14-19-59-41/MaxText/max_utils.py", line 362, in setup_initial_state
    state, raw_params = checkpointing.load_state_if_possible(checkpoint_manager,
  File "/home/.../2024-02-14-19-59-41/MaxText/checkpointing.py", line 116, in load_state_if_possible
    full_restored_state = checkpointer.restore(p, item = abstract_param_train_state,\
  File "/home/.../.local/lib/python3.10/site-packages/orbax/checkpoint/checkpointer.py", line 166, in restore
    restored = self._handler.restore(directory, args=ckpt_args)
  File "/home/.../.local/lib/python3.10/site-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 1073, in restore
    restored_item = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/.../.local/lib/python3.10/site-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 903, in _maybe_deserialize
    deserialized_batches += await asyncio.gather(*deserialized_batches_ops)
  File "/home/.../.local/lib/python3.10/site-packages/orbax/checkpoint/type_handlers.py", line 1179, in deserialize
    results = await super().deserialize(infos, args)
  File "/home/.../.local/lib/python3.10/site-packages/orbax/checkpoint/type_handlers.py", line 1117, in deserialize
    await _assert_parameter_files_exist(
  File "/home/.../.local/lib/python3.10/site-packages/orbax/checkpoint/type_handlers.py", line 260, in _assert_parameter_files_exist
    raise FileNotFoundError(
FileNotFoundError: Individual parameter subdirectory not found at path: gs://.../.../param_checkpoint/checkpoints/0/default/step
```
Thus, it’s trying to find `gs://.../.../param_checkpoint/checkpoints/0/default/step`  dir, whereas there is no such. 

Passing the initial checkpoint path `gs://.../checkpoints/10000/default` to the `decode.py` did not lead to the desired result:
```bash
ValueError: Dict key mismatch; expected keys: ['decoder_norm', 'layers', 'logits_dense']; dict: {'decoder_norm': {'scale': ArrayRestoreArgs(restore_type=None, dtype=dtype('float32'), mesh=Mesh(device_ids=array([[[[[0],
          [2],
          [1],
          [3]]]]]), axis_names=('data', 'fsdp', 'sequence', 'tensor', 'autoregressive')), mesh_axes=PartitionSpec(('fsdp', 'sequence'),), sharding=None, global_shape=None)}, 'layers_0': {'mlp': {'wi_0': {'kernel': ArrayRestoreArgs(restore_type=None, dtype=dtype('float32'), mesh=Mesh(device_ids=array([[[[[0],
          [2],
          [1],
          [3]]]]]), axis_names=('data', 'fsdp', 'sequence', 'tensor', 'autoregressive')), mesh_axes=PartitionSpec(('fsdp', 'sequence'), ('tensor', 'autoregressive')), sharding=None, global_shape=None)}, 'wi_1': {'kernel': ArrayRestoreArgs(restore_type=None, dtype=dtype('float32'), mesh=Mesh(device_ids=array([[[[[0],
...
```
I also tried to train a model `async_checkpointing: False` , thinking that there could be a problem with asynchronous checkpointing, but got the same result. What is the problem? Should I pass the number of training steps of the checkpoint? 

I'd be grateful for any advice on how to resolve the issue.

**Comment by rwitten** [comment]
This was fixed by an upgraded MaxText.
